#!/bin/bash -e

FETCHED_DIR="fetched"
API_DIR="api"
API_SOURCE_URI="https://swapi.co/api/"
API_MIRROR_URI="https://gotev.github.io/swapi-android/"

function fetch {
  echo "fetching $1 ..."

  for pageNumber in `seq 1 $2`
  do
    page="https://swapi.co/api/$1/?page=${pageNumber}"
    echo "  $page"
    file_name="${FETCHED_DIR}/${1}_page${pageNumber}.json"
    curl -s -L "$page" -o /tmp/swapifetch
    python -m json.tool /tmp/swapifetch > "$file_name"
    rm -rf /tmp/swapifetch

    mkdir -p "${API_DIR}/${1}"
    api_file_name="${API_DIR}/${1}/page${pageNumber}.json"
    cat "$file_name" | sed "s*${API_SOURCE_URI}*${API_MIRROR_URI}*g" > "$api_file_name"
  done
}

function recreate {
  rm -rf "$1"
  mkdir "$1"
}

recreate "$FETCHED_DIR"
recreate "$API_DIR"

fetch "starships" "4"
fetch "people" "9"
fetch "planets" "7"
fetch "films" "1"
fetch "species" "4"
fetch "vehicles" "4"

echo "Moving APIs to GitHub Pages Directory..."
rm -rf ../docs/api
mv api/ ../docs/

echo
echo "Fetching DONE!"
