package net.gotev.swapi.models

/**
 * Enumeration of all the manufacturers.
 */
enum class Manufacturer(val rawValue: String) {
    AllanteenSixShipyards(rawValue = "allanteen six shipyards"),
    AllianceUndergroundEngineering(rawValue = "alliance underground engineering"),
    AppazannaEngineeringWorks(rawValue = "appazanna engineering works"),
    AratechRepulsorCompany(rawValue = "aratech repulsor company"),
    BaktoidArmorWorkshop(rawValue = "baktoid armor workshop"),
    BaktoidFleetOrdnance(rawValue = "baktoid fleet ordnance"),
    BespinMotors(rawValue = "bespin motors"),
    BotajefShipyards(rawValue = "botajef shipyards"),
    CollaDesigns(rawValue = "colla designs"),
    CorelliaMiningCorporation(rawValue = "corellia mining corporation"),
    CorellianEngineeringCorporation(rawValue = "corellian engineering corporation"),
    CygnusSpaceworks(rawValue = "cygnus spaceworks"),
    DeslerGizhOutworldMobilityCorporation(rawValue = "desler gizh outworld mobility corporation"),
    FeethanOttrawScalableAssemblies(rawValue = "feethan ottraw scalable assemblies"),
    FondorShipyards(rawValue = "fondor shipyards"),
    FreeDacVolunteersEngineeringCorps(rawValue = "free dac volunteers engineering corps"),
    GallofreeYards(rawValue = "gallofree yards"),
    GworiRevolutionarySystems(rawValue = "gwori revolutionary industries"),
    HaorChallEngineering(rawValue = "haor chall engineering"),
    HupplaPasaTiscShipwrightsCollective(rawValue = "huppla pasa tisc shipwrights collective"),
    HoerschKesselDrive(rawValue = "hoersch-kessel drive"),
    ImperialDepartmentOfMilitaryResearch(rawValue = "imperial department of military research"),
    IncomCorporation(rawValue = "incom corporation"),
    Incorporated(rawValue = "incorporated"),
    KuatDriveYards(rawValue = "kuat drive yards"),
    KuatSystemsEngineering(rawValue = "kuat systems engineering"),
    KoensayrManufacturing(rawValue = "koensayr manufacturing"),
    MobquetSwoopsAndSpeeders(rawValue = "mobquet swoops and speeders"),
    MonCalamariShipyards(rawValue = "mon calamari shipyards"),
    NarglatchAirtechPrefabricatedKit(rawValue = "narglatch airtech prefabricated kit"),
    NubiaStarDrives(rawValue = "nubia star drives"),
    OtohGungaBongamekenCooperative(rawValue = "otoh gunga bongameken cooperative"),
    PhlacArphoccAutomataIndustries(rawValue = "phlac-arphocc automata industries"),
    Razalon(rawValue = "razalon"),
    RendiliStardrive(rawValue = "rendili stardrive"),
    RepublicSienarSystems(rawValue = "republic sienar systems"),
    RothanaHeavyEngineering(rawValue = "rothana heavy engineering"),
    SienarFleetSystems(rawValue = "sienar fleet systems"),
    SlaynKorpil(rawValue = "slayn & korpil"),
    SoroSuubCorporation(rawValue = "sorosuub corporation"),
    SubproCorporation(rawValue = "subpro corporation"),
    TechnoUnion(rawValue = "techno union"),
    TheedPalaceSpaceVesselEngineeringCorps(rawValue = "theed palace space vessel engineering corps"),
    UbrikkianIndustries(rawValue = "ubrikkian industries"),
    UbrikkianIndustriesCustomVehicleDivision(rawValue = "ubrikkian industries custom vehicle division"),
    Unknown(rawValue = "unknown"),
    ZgomotTernbuellGuppatCorporation(rawValue = "z-gomot ternbuell guppat corporation")
}
